version: "3.9"

services:

  db:
    image: mysql:8.4
    container_name: smartspend-db-dev
    restart: always

    environment:
      MYSQL_DATABASE: ${DB_NAME_DEV}
      MYSQL_USER: ${DB_USERNAME_DEV}
      MYSQL_PASSWORD: ${DB_PASSWORD_DEV}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_DEV}

    volumes:
      - db_data_dev:/var/lib/mysql

    ports:
      - "3307:3306"  # Puerto diferente para desarrollo

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ${DOCKER_HUB_USERNAME}/smartspend:dev
    container_name: smartspend-app-dev
    restart: always

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8443:8443"  # Puerto HTTPS desarrollo - perfil prod usa 8443 interno

    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME_DEV}
      DB_USERNAME: ${DB_USERNAME_DEV}
      DB_PASSWORD: ${DB_PASSWORD_DEV}

      JWT_SECRET: ${JWT_SECRET_DEV}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD_DEV}

volumes:
  db_data_dev:
