logging:
  level:
    org.springframework.boot.web.embedded.tomcat: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
  pattern:
    console: "ðŸ”¥ PERFIL PROD ACTIVO ðŸ”¥ - %d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:smartspend}
    key-alias: smartspend-ssl
    key-store-type: PKCS12

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:smartspend}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:smartspend}
    password: ${DB_PASSWORD:smartspend_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: always

